x-netos-env: &netos-env
  NETOS_TOPOLOGY_DIR: /opt/netos/topology/2-node

x-netos-node: &netos-node
  build:
    context: ..
    dockerfile: infra/Dockerfile
  volumes:
    - ./topology/2-node:/opt/netos/topology/2-node:ro

services:
  node1:
    <<: *netos-node
    environment:
      <<: *netos-env
      NETOS_NODE_ID: node1

  node2:
    <<: *netos-node
    depends_on:
      - node1
    environment:
      <<: *netos-env
      NETOS_NODE_ID: node2
