services:
  node1:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - topology/2-node/node1.env

  node2:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    depends_on:
      - node1
    env_file:
      - topology/2-node/node2.env
